/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.helloworld;

import com.google.inject.Injector;
import com.helloworld.transactions.TransactionsService;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class JavaFXApplication extends Application {
    
    TransactionsService transactionsService;
    
    private static Injector injector;

    public JavaFXApplication() {
        this.transactionsService = injector.getInstance(TransactionsService.class);
    }

    public static void setInjector(Injector injector) {
        JavaFXApplication.injector = injector;
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle("JavaFX Hello World");
        
        Label field = new Label();
        field.setText(String.join(", ", transactionsService.getTransactions()));

        StackPane root = new StackPane();
        root.getChildren().add(field);
        stage.setScene(new Scene(root, 300, 250));
        stage.show();
    }
}
