/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafxvalidation.demo;

import com.javafxvalidation.form.ValidateableTextFieldBox;
import com.javafxvalidation.validators.MinLengthValidator;
import com.javafxvalidation.validators.NotEmptyValidator;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class JavaFXApplication extends Application {
    
    private VBox root;

    @Override
    public void start(Stage stage) {
        stage.setTitle("JavaFX Hello World");
        
        root = new VBox();
        stage.setScene(new Scene(root, 300, 250));
        stage.show();
        
        initialize();
    }
    
    private void initialize() {
        var box1 = new ValidateableTextFieldBox(new NotEmptyValidator(), new MinLengthValidator(3));
        box1.setMaxWidth(300);
        var box2 = new ValidateableTextFieldBox(new NotEmptyValidator(), new MinLengthValidator(5));
        box2.setMaxWidth(300);
        
        root.getChildren().addAll(box1, box2);
    }
}
