/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafxvalidation.demo;

import com.javafxvalidation.utils.FormBuilder;
import com.javafxvalidation.validators.MinLengthValidator;
import com.javafxvalidation.validators.NotEmptyValidator;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class JavaFXApplication extends Application {
    
    private VBox root;

    @Override
    public void start(Stage stage) {
        stage.setTitle("JavaFX Hello World");
        
        root = new VBox();
        stage.setScene(new Scene(root, 300, 250));
        stage.show();
        
        initialize();
    }
    
    private void initialize() {
        root.getChildren().add(FormBuilder.addTextFieldBox(new NotEmptyValidator(), new MinLengthValidator(3)));
        root.getChildren().add(FormBuilder.addTextFieldBox(new NotEmptyValidator(), new MinLengthValidator(5)));
    }
}
